title: Jon Deng Portfolio
description: Jon Deng's Portfolio

url: https://jondeng.com
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Writing
   url: /articles

social:
   github: dengjonathan
   twitter: jondeng
