title: Jon Deng
description: Jon Deng's Portfolio Site and Blog

url: http://jon.deng.com
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Writing
   url: /writing

social:
   github: dengjonathan
   twitter: jondeng

# gems:
#   - jemoji